### ISSUE TITLE
Error on start

### ISSUE THREAD

**Issue by 53RG1005** [d1ceward/dokku-posteio#8]
dokku posteio:start --disable-clamav
-----> Starting container
docker: invalid reference format.
See 'docker run --help'.

**Comment by 53RG1005** [comment]
Fresh install dokku and plugin

**Comment by d1ceward** [comment]
There was an error with the internal docker call and toggleable options, this should be fixed with the new version 1.6.8

**Comment by 53RG1005** [comment]
> There was an error with the internal docker call and toggleable options, this should be fixed with the new version 1.6.8

It starts, thank you!

But i got another one problem. I set the domain but it still "Welcome to nginx!"

**Comment by 53RG1005** [comment]
What am I doing wrong?

I see docker ps 

6c4ad7ac482c   analogic/poste.io:2.3.11          "/init"                  3 seconds ago    Up 2 seconds (health: starting)   0.0.0.0:25->25/tcp, :::25->25/tcp, 0.0.0.0:110->110/tcp, :::110->110/tcp, 80/tcp, 0.0.0.0:143->143/tcp, :::143->143/tcp, 0.0.0.0:465->465/tcp, :::465->465/tcp, 0.0.0.0:587->587/tcp, :::587->587/tcp, 0.0.0.0:993->993/tcp, :::993->993/tcp, 443/tcp, 0.0.0.0:995->995/tcp, :::995->995/tcp, 4190/tcp   dokku.posteio

**Comment by 53RG1005** [comment]
It's looks like a proxy problem, but how to solve it? It's not dokku app where you can simply add domain)

**Comment by 53RG1005** [comment]
I thought it created a config for nginx :)
I created it manually and it's ok.)
